server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/aggregate
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  application:
    name: Aggregate-Service
  config:
    import: configserver:http://localhost:9286